function toFrontendFixture(candidate) {
  return {
    snapshot: candidate.snapshot,
    observations: candidate.observations.map((item) => ({
      observation_id: item.observation_id,
      region_id: item.region_id,
      disease_id: item.disease_id,
      age: item.age,
      risk_level: item.risk_level,
      trend_summary: item.trend_summary,
    })),
    forecasts: candidate.forecasts.map((item) => ({
      forecast_id: item.forecast_id,
      region_id: item.region_id,
      disease_id: item.disease_id,
      age: item.age,
      week_direction: item.week_direction,
      month_direction: item.month_direction,
      confidence: item.confidence,
    })),
    breakdowns: candidate.breakdowns,
  };
}

export function buildMockSnapshotFixture(candidate) {
  return `// This file is generated by \`npm run analytics:mock\`.
// Do not edit this file manually.
import type {
  ForecastRecord,
  ObservationBreakdownResponse,
  ObservationRecord,
} from "@/shared/api/types";

interface MockSnapshotCandidateFixture {
  snapshot: {
    snapshot_id: string;
    status: string;
    observed_until: string;
    published_at: string | null;
    forecast_generated_at: string;
    source_note: string;
  };
  observations: ObservationRecord[];
  forecasts: ForecastRecord[];
  breakdowns: Array<
    ObservationBreakdownResponse & {
      region_id: string;
      disease_id: string;
      age: number;
    }
  >;
}

export const mockSnapshotCandidate = ${JSON.stringify(toFrontendFixture(candidate), null, 2)} satisfies MockSnapshotCandidateFixture;
`;
}
