import { describe, expect, it } from "vitest";
import { buildMockSnapshotFixture } from "./mockSnapshotFixture.mjs";

describe("buildMockSnapshotFixture", () => {
  it("serializes a snapshot candidate as a typed frontend fixture", () => {
    const source = {
      snapshot: {
        snapshot_id: "draft-2026-04-09",
        status: "draft",
        observed_until: "2026-04-09",
        published_at: null,
        forecast_generated_at: "2026-04-09",
        source_note: "mock analytics candidate generated from normalized records",
      },
      observations: [
        {
          observation_id: "obs-31023-flu-a-7-2026-04-09",
          region_id: "31023",
          disease_id: "flu-a",
          age: 7,
          risk_level: "high",
          trend_summary: "최근 관측 기준 위험 증가 가능성이 높음",
          observed_on: "2026-04-09",
          case_count: 22,
        },
      ],
      forecasts: [
        {
          forecast_id: "fc-31023-flu-a-7-2026-04-09",
          region_id: "31023",
          disease_id: "flu-a",
          age: 7,
          week_direction: "increase",
          month_direction: "steady",
          confidence: "medium",
          generated_from_date: "2026-04-09",
        },
      ],
      breakdowns: [],
    };

    const fixture = buildMockSnapshotFixture(source);

    expect(fixture).toContain("This file is generated by `npm run analytics:mock`.");
    expect(fixture).toContain("ObservationRecord");
    expect(fixture).toContain("export const mockSnapshotCandidate = {");
    expect(fixture).toContain('"observation_id": "obs-31023-flu-a-7-2026-04-09"');
    expect(fixture).not.toContain("observed_on");
    expect(fixture).not.toContain("case_count");
    expect(fixture).not.toContain("generated_from_date");
    expect(fixture).toContain("satisfies MockSnapshotCandidateFixture");
  });
});
